language: php

php:
  - 5.6
  - 7.0

env:
  - DB=mysql

before_install:
  - openssl aes-256-cbc -K $encrypted_38f96163e3a4_key -iv $encrypted_38f96163e3a4_iv -in .travis/deploy.key.enc -out .travis/deploy.key -d
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-docutils openjdk-7-jre

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS phpofby;" -uroot; fi

script:
  - php phing.phar build-ci

addons:
  ssh_known_hosts: php.of.by

after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy.key
  - ssh-add .travis/deploy.key
  - sh ./bin/run-prod-build.sh
  - rm -Rf build
  - mkdir build
  - mv * build
  - tar -czf package.tgz build
  - scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
  - ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh
