deploy:
  master:
    server: karma.vps-private.net
    username: zenci
    dir: '{home}/github/{repo_owner}/{repo_name}/{branch}'
    env_vars:
      docroot: '{home}/domains/phpofby.examples.zen.ci'
      domain: phpofby.examples.zen.ci
    scripts:
      after: '{deploy_dir}/bin/after.php'
