deploy:
  master:
    server: karma.vps-private.net
    username: zenci
    dir: '{home}/github/{repo_owner}/{repo_name}/{branch}'
    env_vars:
      docroot: '{home}/domains/phpofby.examples.zen.ci'
      domain: phpofby.examples.zen.ci
    scripts:
      after: '{deploy_dir}/bin/after.php'
test:
  php70:
    branch:
      box: 'dual-leam-php70'
      dir: '{home}/buildir'
      scripts:
        init: '{deploy_dir}/bin/init_test.sh'
      tests:
        - '{deploy_dir}/bin/run_test.sh'
    pull_request:
      box: 'dual-leam-php70'
      dir: '{home}/buildir'
      scripts:
        init: '{deploy_dir}/bin/init_test.sh'
      tests:
        - '{deploy_dir}/bin/run_test.sh'
